<?php require_once('views/templates/header.phtml'); ?>

    <div class="grid bg-emerald">
        <div class="row cells1">
            <div class="main">
                <div class="cell">
                    <h2>Welcome to Postflix</h2>
                    <p>Welcome <?php echo $view->user->getName(); ?> to Postflix, we're sure you'll love it here. You are now free to view and rent
                    our DVDs, set up your own profile and get started in the Postflix community.</p>
                    <p>Here are some things to get you started:
                    <ul>
                        <li>Rent your first DVD</li>
                        <li>Browse our collections</li>
                        <li>Find your favourite genre</li>
                        <li>View your profile</li>
                        <li>Edit your Wishlist</li>
                        <li>Read our guides</li>
                    </ul></p>
                </div>
            </div>
        </div>
    </div>

<?php require_once('views/templates/footer.phtml'); ?>